version: 2.1
defaults: &defaults
  docker:
    - image: circleci/node:latest

jobs:
  setup_dx:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Salesforce DX
          command: |
            openssl enc -aes-256-cbc -md sha256 -salt -d -in assets/server.key.enc -out assets/server.key -k $SERVER_KEY_PASSWORD -pbkdf2
            export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
            export SFDX_DOMAIN_RETRY=300
            npm install sfdx-cli
            node_modules/sfdx-cli/bin/run --version
            node_modules/sfdx-cli/bin/run plugins --core
      - run:
          name: Authenticate DevHub
          command: |
            node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid $SF_CONSUMER_KEY --jwtkeyfile $PWD/assets/server.key --username $SF_USERNAME --setdefaultdevhubusername -a HubOrg
      - persist_to_workspace:
          root: ~/
          paths:
            - .sfdx/*
            - project/*
  prerequesites:
    <<: *defaults
    steps: # steps that comprise the `build` job
      - attach_workspace:
          at: ~/
      - run:
          name: "echo"
          command: |
            ls -al

workflows:
  version: 2
  prerequesites:
    jobs:
      - setup_dx
      - prerequesites:
          requires:
            - setup_dx
          filters:
            branches: 
              only: /feature.*/

  