version: 2.1
executors:
  my-executor:
    docker:
      - image: lingjun/sfdx:latest

jobs:
  prerequesites:
    executor: my-executor # run the seps with executor
    working_directory: ~/workspace
    steps: # steps that comprise the `build` job
      - checkout # checkout the source code to working directory
      - run: 
          name: "Decrypt server key"
          command: |
            openssl enc -aes-256-cbc -md sha256 -salt -d -in assets/server.key.enc -out assets/server.key -k $SERVER_KEY_PASSWORD -pbkdf2
            ls -al
            ls assets/ -al
      - run:
          name: "Set Environment Variables"
          command: |
            export SFDX_LOG_LEVEL=DEBUG
            export SFDX_DOMAIN_RETRY=600
            export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true

  build_and_testing:
    executor: my-executor # run the seps with executor
    working_directory: ~/workspace
    steps:
      - run:
          name: "Build and Unit Testing"
          command: |
            # Authenticate to the Dev Hub using the server key
            sfdx force:auth:jwt:grant --setdefaultdevhubusername --clientid $SF_CONSUMER_KEY --jwtkeyfile $PWD/assets/server.key --username $SF_USERNAME
            # Create scratch org
            sfdx force:org:create --setdefaultusername --definitionfile config/project-scratch-def.json --wait 10 --durationdays 7
            # Display scratch org details
            sfdx force:org:display
            # Push source to scratch org (this is with source code, all files, etc)
            sfdx force:source:push
            # Assign DreamHouse permission set to scratch org default user
            ## sfdx force:user:permset:assign --permsetname DreamHouse
            # Add sample data into app
            ## sfdx force:data:tree:import --plan data/sample-data-plan.json
            # Unit Testing
            sfdx force:apex:test:run --wait 10 --resultformat human --codecoverage --testlevel RunLocalTests
            # Delete Scratch Org
            sfdx force:org:delete --noprompt

workflows:
  version: 2
  prerequesites:
    jobs:
      - prerequesites:
          filters:
            branches: 
              only: /feature.*/
      - build_and_unit_testing:
          requires:
            - prerequesites
          filters:
            branches:
              only: /feature.*/

  